# Generated by Django 4.2.5 on 2023-09-24 14:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_rename_contact_number_userprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
            ],
            options={
                'db_table': 'store_rating',
            },
        ),
        migrations.CreateModel(
            name='FavoriteStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('favorited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.userprofile')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.store')),
            ],
            options={
                'db_table': 'favorite_store',
            },
        ),
    ]
