# Generated by Django 4.2.5 on 2023-11-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_remove_size_service_service_sizes'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='size',
            table='size',
        ),
    ]
