# Generated by Django 4.2.5 on 2023-11-11 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_order_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='doc_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='orientation',
        ),
        migrations.AddField(
            model_name='order',
            name='doc_type',
            field=models.CharField(default='pdf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orientation',
            field=models.PositiveIntegerField(choices=[(1, 'Portrait'), (2, 'Landscape')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='store_app.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='store_app.size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='store_app.store'),
            preserve_default=False,
        ),
    ]
