# Generated by Django 4.2.5 on 2023-12-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_remove_service_doc_type_remove_service_orientation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
