# Generated by Django 4.2.5 on 2023-12-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_contact_number_userprofile_mobile_number_and_more'),
        ('store_app', '0007_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='store_user', to='user_app.userprofile'),
            preserve_default=False,
        ),
    ]
