# Generated by Django 4.2.5 on 2023-12-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_contact_number_userprofile_mobile_number_and_more'),
        ('store_app', '0008_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_user', to='user_app.userprofile'),
        ),
    ]
