# Generated by Django 4.2.5 on 2024-01-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_userprofile_image'),
        ('store_app', '0010_alter_favoritestore_favorited_by_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritestore',
            unique_together={('favorited_by', 'store')},
        ),
    ]
