# Generated by Django 4.2.5 on 2024-01-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0014_alter_favoritestore_favorited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storerating',
            name='store',
        ),
        migrations.AddField(
            model_name='store',
            name='ratings',
            field=models.ManyToManyField(related_name='store_ratings', to='store_app.storerating'),
        ),
    ]
