# Generated by Django 4.2.5 on 2024-01-26 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0015_remove_storerating_store_store_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='ratings',
        ),
        migrations.AddField(
            model_name='storerating',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_rating_store', to='store_app.store'),
            preserve_default=False,
        ),
    ]
