# Generated by Django 4.2.5 on 2023-12-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0002_rename_contact_number_userprofile_mobile_number_and_more'),
        ('store_app', '0007_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('doc_type', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orientation', models.PositiveIntegerField(choices=[(1, 'Portrait'), (2, 'Landscape')], default=1)),
                ('notes', models.TextField(blank=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service', to='store_app.service')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_size', to='store_app.size')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_store', to='store_app.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user', to='user_app.userprofile')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
