# Generated by Django 4.2.5 on 2024-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orientation',
            field=models.PositiveIntegerField(choices=[(0, 'In Progress'), (1, 'Cancelled'), (2, 'Completed')], default=0),
        ),
    ]
