# Generated by Django 4.2.5 on 2023-09-24 14:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('report_type', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'report_type',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.URLField(blank=True, max_length=250, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=256, null=True)),
                ('paid_access', models.BooleanField(default=False)),
                ('handicap_number', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-36.0), django.core.validators.MaxValueValidator(36.0)])),
                ('allow_notifications', models.BooleanField(default=True)),
                ('golf_home_course_name', models.CharField(blank=True, max_length=256, null=True)),
                ('golf_home_course_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ghin_number', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('is_ghin_verified', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('N', 'Not specified'), ('M', 'Male'), ('F', 'Female')], default='N', max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserBetPaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('payment_method_name', models.CharField(max_length=50)),
                ('payment_method_url', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_payments_info', to='user_app.userprofile')),
            ],
            options={
                'db_table': 'user_bet_payment_info',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.reporttype')),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportee', to='user_app.userprofile')),
                ('reportee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='user_app.userprofile')),
            ],
            options={
                'db_table': 'report_user',
            },
        ),
        migrations.CreateModel(
            name='FavouritePlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('favourite_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='user_app.userprofile')),
                ('followed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_player', to='user_app.userprofile')),
            ],
            options={
                'db_table': 'favourite_players',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='favouriteplayers',
            constraint=models.UniqueConstraint(fields=('favourite_player', 'followed_by'), name='user_pair'),
        ),
    ]
