# Generated by Django 4.2.5 on 2023-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ghin_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='golf_home_course_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='golf_home_course_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='handicap_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_ghin_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paid_access',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='stripe_customer_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
