# Generated by Django 4.2.5 on 2024-01-26 09:49

from django.db import migrations, models
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_rename_contact_number_userprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user_app.models.UserProfile.user_profile_dir),
        ),
    ]
